CREATE DATABASE mydb_java;

-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 16:40:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_java` DEFAULT CHARACTER SET utf8 ;
USE `mydb_java` ;

-- -----------------------------------------------------
-- Table `mydb_java`.`hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_java`.`hero` (
                                                  `id` INT NOT NULL,
                                                  `type` VARCHAR(15) NULL,
    `name` VARCHAR(45) NULL,
    `life` INT NULL,
    `strength` INT NULL,
    `offensiveItem` VARCHAR(45) NULL,
    `defensiveItem` VARCHAR(45) NULL,
    `playerPos` INT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;